### ISSUE TITLE
Trouble Unsubscribing to Playlists

### ISSUE THREAD

**Issue by Brancliff** [bbilly1/tubearchivist#94] opened 2021-11-29 04:28 UTC
Loving the v0.0.8 release! Playlists were one of the features I wanted most so I'm super jazzed to see that they're here. Makes it a lot easier. For a lot of channels who make a web series, maybe you want 'the episodes' of the series but maybe not like, everything they do.

Anyways- I'm having trouble unsubscribing to playlists. It's weird- you just have to click "unsubscribe" and that's it, right? But I hit unsubscribe, and if I refresh or revisit the page, it's just still there on the "only playlists I am subscribed to" view of the playlists page.

I've already tried restarting the containers and restarting my NAS. I saw that [someone else had trouble with their space](https://github.com/bbilly1/tubearchivist/issues/91), but I'm at 88%, and the problems start at 95%, right?

Here's just a tiny bit of the logs of me trying to do this, although uh- I'm not sure if it'll tell much --> https://pastebin.com/p9AZNJbW

**EDIT**: at the end of this post, I requested the ability to download a playlist without subscribing to it- but it turns out you can do that by just putting the playlist in the downloads page and not in the playlists page. whoops

**Comment by bbilly1** [comment] 2021-11-29 07:04
Thanks for your kind words, means a lot. :)

I see where the problem is, it's with the old playlist id format, 18 characters long. Subscribing worked, because I assume you entered the whole URL into the form? But unsubscribing fails due to it not recognizing the short playlist id. Easy fix, will be in the next version, thanks for pointing it out!

But yes, at 95% things break, but maybe best not to let it get that far to begin with... 

I'm glad you found the download playlist thing, now thinking of it, wouldn't it be great that when downloading a playlist, that this will get indexed as such automatically so you will get the next and previous links? See, that's why it's helpful if people start using things even if it's not perfect yet. How else would you get feedback? :)

**Comment by bbilly1** [comment] 2021-12-17 12:43
I forgot to tag the commit here, but it's now merged in v0.0.9.

**Closed by bbilly1** 2021-12-17 12:43 UTC
