### ISSUE TITLE
Videos cannot play on XUL Browsers

### ISSUE THREAD

**Issue by Brancliff** [bbilly1/tubearchivist#83] opened 2021-11-04 02:25 UTC
**Edit**: I probably should've said, videos _downloaded through tubearchivist_ cannot play on XUL browsers. If I import a video I downloaded through something else, it works just fine.

XUL applications are based on the old Mozilla codebase, but has been gradually shifted out over time. A few examples of XUL browsers are Pale Moon (I'm using this one), Basilisk, and Waterfox.

You could argue that this is a me problem for using weird boomer browsers no one's ever heard of.... And, well, you're right- but when I download the same videos with yt-dlp standalone and drag their mp4s into the browser window, they're able to play just fine. So I know that it's possible, I'm just not sure what would need to happen.

When trying to play a video, an overlay appears over it that says "Video format or MIME type is not supported."

**Comment by bbilly1** [comment] 2021-11-04 04:22
What are the format options are you using for the videos that play through the browser? Could be that this is a codec issue similar to the webkit problem before here #61 where the solution was to use `bestvideo[VCODEC=avc1]+bestaudio[ACODEC=mp4a]/mp4` for the codec or anything similar to that. I mean if you can watch a regular video on youtube, then there is a stream available that's compatible with your browser. The output of `mediainfo` on the video file that's working through the browser would give additional insights.

**Comment by Brancliff** [comment] 2021-11-05 20:56
Entering that into my download settings fixed it completely, thank you! 

But now I have a different problem - Tubearchivist is having trouble with video thumbnails. It actually embeds the thumbnail into the video file just fine, but it seems that the video thumbnails don't appear in the browser, like on the homepage. But the thumbnail is embedded onto the video file, so I know it can get the thumbnails, it just seems to have trouble adding them to the cache folder.

I've already tried redownloading the videos. Rescanning thumbnails actually replaces the video thumbnail with the Tubearchivist default thumbnail. I've also tried a fresh reinstall of Tubearchivist (just in case).

Here are my logs: --> https://pastebin.com/nRDB5PdY
And here's one of the videos having this problem, if that helps: --> https://www.youtube.com/watch?v=cPZP-yC6j70

**Comment by bbilly1** [comment] 2021-11-06 09:46
For the thumbnails, I have it seen fail too on some rare cases, your example url fails for me too, hence the fallback to the default. I've been meaning to look into what's going on but as far as I can say it's a issue from yt-dlp. For some reason the same issue is not present with the `--embed-thumbnail` option as that works for me too. 

I'll do some more research into that, as I wasn't able to reproduce it consistently as it looks like it's only failing to extract the thumbnails when invoking yt-dlp with Python but not when running yt-dlp regularly from the shell. I'll look into it before opening an issue over at yt-dlp to make sure I'm not overlooking something.

**Comment by bbilly1** [comment] 2021-11-06 13:26
OK, figured out that yt-dlp already has a solution for that problem and can `check_formats` already to make sure the thumbnail url is actually available. Will be in the next release or rebuild from testing branch if you can't wait.

**Comment by Brancliff** [comment] 2021-11-07 17:29
Oh, that's great news! But I've got a silly question now... How do I get the testing branch?

So I'm using the docker-compose file, right- it's currently set to "image: bbilly1/tubearchivist:latest". I figured I'd need to try " image: bbilly1/tubearchivist:test" or testing or something along those lines, but neither of those worked for me.

**Comment by bbilly1** [comment] 2021-11-08 06:46
That's OK, everybody starts off from somewhere. The good news is that answers to this kinds of questions are usually not too far away from your favorite search engine and are freely available. For example to get started:
- https://git-scm.com/docs/git-branch
- https://docs.docker.com/engine/reference/commandline/image_build/
- https://www.freecodecamp.org/news/git-clone-branch-how-to-clone-a-specific-branch/
- https://stackify.com/docker-build-a-beginners-guide-to-building-docker-images/

But yes, obviously not everybody in the world is going to be interested in learning these things, hence the convenient docker image.

**Closed** 2021-11-10 09:49 UTC
